spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task
    username: root
    password: udeshi123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
server:
  port: 8081
